project:
  type: website
  output-dir: docs

website:
  title: "Pedrógão Grande Reburn Susceptibility"
  favicon: favicon.png
  search: true

  navbar:
    right:
      - icon: github
        href: https://github.com/weichen221/casa00026_Big_Data

format:
  html:
    theme:
      light: united
      dark: superhero
    toc: true
    toc-depth: 3
    toc-location: right
    page-layout: full
    smooth-scroll: true
    code-fold: true
    code-tools: true
    number-sections: true
    link-external-newwindow: true
    css: styles.css
    title-block-banner: images/hero-bg.jpg
    title-block-banner-color: white
    grid:
      sidebar-width: 0px
      margin-width: 420px
      body-width: 1500px
      gutter-width: 1rem

execute:
  echo: false
  warning: false
  message: false
